#!/bin/sh
cd assets/works/
[ -d thumbs ]  ||  mkdir thumbs

cd images
find * -maxdepth 1 -type d -print | xargs -I {} mkdir -p ../thumbs/{}

find . -name *.png | xargs  -I {} convert -resize 500x250 {} ../thumbs/{}
