[build]
  publish = "public/"
  command = "npm run build"

[[redirects]]
  from = "/openvis-react"
  to = "http://ilyabo.github.com/openvis-react/"
  status = 301

[[redirects]]
  from = "/p/gflowiz-talk"
  to = "/talks/2015-04-03-openvis/"
  status = 301

[[redirects]]
  from = "/p/react-meetup-2018"
  to = "/talks/2018-07-11-react-meetup/"
  status = 301

[[redirects]]
  from = "/p/react-meetup-2015"
  to = "/talks/2015-11-27-react-meetup/"
  status = 301

[[redirects]]
  from = "/p/flowmap-3d"
  to = "/p/stellar-commutes/"
  status = 301
